/**
 * Emits the token set as Tailwind v4 CSS.
 *
 * This exists so the web app never restates a token value. `globals.css`
 * imports the generated stylesheet, which means a change in `color.ts` reaches
 * the browser without anyone hand-editing CSS, and web and mobile cannot drift.
 *
 * ## The @theme / @media rule
 *
 * Tailwind v4 must never see `@theme` nested inside `@media`. It does not
 * error - it silently merges the nested block into the base theme, so the dark
 * values become the only values and light mode disappears. This cost Phase 0
 * real time (see HANDOFF.md and the emitted-CSS test).
 *
 * The correct shape, which this module always produces:
 *
 *   @theme { --color-background: <light>; }          // top level, light only
 *   @media (prefers-color-scheme: dark) {
 *     :root:not(.light) { --color-background: <dark>; }   // plain vars, no @theme
 *   }
 *   :root.dark { --color-background: <dark>; }            // manual override
 */
import { dark, light, type ColorScheme } from './color.js';
import { radius } from './radius.js';
import { spacing } from './spacing.js';
import { fontFamily, typography, type TypeToken } from './typography.js';

/** Base grid step. Tailwind v4 derives `p-4`, `gap-2`, etc. from this. */
const SPACING_BASE_PX = spacing[1];

function colorVars(scheme: ColorScheme, indent: string): string {
  return Object.entries(scheme)
    .map(([role, value]) => `${indent}--color-${kebab(role)}: ${value};`)
    .join('\n');
}

/** `foregroundMuted` -> `foreground-muted`, so CSS vars read as CSS. */
function kebab(value: string): string {
  return value.replace(/[A-Z]/g, (c) => `-${c.toLowerCase()}`);
}

/**
 * Font stacks indirect through `--font-*-loaded` so a host that self-hosts the
 * faces can inject its own family name. next/font generates an obfuscated name
 * ('__Manrope_a1b2c3') and a bare 'Manrope' would silently never match it. When
 * nothing sets the hook, the plain family name is used.
 */
function fontVars(): string {
  return [
    `  --font-display: var(--font-display-loaded, '${fontFamily.display}'), ui-sans-serif, system-ui, sans-serif;`,
    `  --font-body: var(--font-body-loaded, '${fontFamily.body}'), ui-sans-serif, system-ui, sans-serif;`,
  ].join('\n');
}

function textVars(): string {
  return (Object.keys(typography) as TypeToken[])
    .flatMap((token) => {
      const level = typography[token];
      return [
        `  --text-${token}: ${level.size}px;`,
        `  --text-${token}--line-height: ${level.lineHeight}px;`,
        `  --text-${token}--font-weight: ${level.weight};`,
        `  --text-${token}--letter-spacing: ${level.letterSpacing}em;`,
      ];
    })
    .join('\n');
}

function radiusVars(): string {
  return Object.entries(radius)
    .map(([token, value]) => `  --radius-${token}: ${value}px;`)
    .join('\n');
}

/**
 * Returns the full Tailwind v4 theme stylesheet for the design system.
 *
 * The caller is responsible for `@import 'tailwindcss'` - this emits only the
 * theme so it can be imported into any Tailwind entrypoint.
 */
export function toTailwindCss(): string {
  return `/*
 * GENERATED by @finmanager/tokens - do not edit by hand.
 * Edit packages/tokens/src/*.ts and rebuild.
 *
 * @theme is top-level and holds LIGHT values only. Dark mode overrides the
 * plain CSS variables. Never nest @theme inside @media: Tailwind v4 silently
 * merges it into the base theme and light mode dies.
 */

@theme {
${colorVars(light, '  ')}

${fontVars()}

  --spacing: ${SPACING_BASE_PX}px;

${radiusVars()}

${textVars()}
}

/* System preference, unless the user has explicitly forced light. */
@media (prefers-color-scheme: dark) {
  :root:not(.light) {
${colorVars(dark, '    ')}
  }
}

/* Explicit user choice always wins over the system preference. */
:root.dark {
${colorVars(dark, '    ')}
}
`;
}
