/**
 * Emits the token set for NativeWind (Tailwind v3) on mobile.
 *
 * Mobile is on Tailwind v3 because stable NativeWind targets v3 while web is on
 * v4 (see D-016). That split is a build-tooling detail, not a design one: both
 * platforms are generated from the same tokens here, so the two apps cannot
 * drift apart visually even though they compile through different Tailwind
 * majors.
 *
 * Colors go through CSS variables holding bare RGB channels, which is what lets
 * `dark:` work at runtime and keeps `bg-primary/10` composing an alpha.
 */
import { dark, light, toRgbChannels, type ColorScheme } from './color.js';
import { radius } from './radius.js';
import { spacing } from './spacing.js';
import { typography, type TypeToken } from './typography.js';

/** `foregroundMuted` -> `foreground-muted`. */
function kebab(value: string): string {
  return value.replace(/[A-Z]/g, (c) => `-${c.toLowerCase()}`);
}

function channelVars(scheme: ColorScheme, indent: string): string {
  return Object.entries(scheme)
    .map(([role, hex]) => `${indent}--color-${kebab(role)}: ${toRgbChannels(hex)};`)
    .join('\n');
}

/**
 * The stylesheet NativeWind compiles as its input.
 *
 * Unlike the web output there is no `@theme` here: that is a Tailwind v4
 * construct. v3 reads its theme from tailwind.config.js instead, so this file
 * carries only the variables that config points at.
 */
export function toNativeWindCss(): string {
  return `/*
 * GENERATED by @finmanager/tokens - do not edit by hand.
 * Edit packages/tokens/src/*.ts and rebuild.
 *
 * Channels are bare (15 118 110) so tailwind.config.js can wrap them in
 * rgb(... / <alpha-value>) and keep opacity utilities working.
 */
@tailwind base;
@tailwind components;
@tailwind utilities;

@layer base {
  :root {
${channelVars(light, '    ')}
  }

  .dark:root {
${channelVars(dark, '    ')}
  }
}
`;
}

type ThemeColors = Record<string, string>;

function colorTheme(): ThemeColors {
  return Object.fromEntries(
    Object.keys(light).map((role) => [
      kebab(role),
      `rgb(var(--color-${kebab(role)}) / <alpha-value>)`,
    ]),
  );
}

/**
 * Sizes carry no fontWeight on mobile.
 *
 * React Native does not synthesise weights for a custom font: asking for
 * weight 800 on a family that only has the regular face silently renders
 * regular on Android. Weight is therefore selected by picking an explicit
 * family below, not by a `fontWeight` utility.
 */
function fontSizeTheme(): Record<string, [string, { lineHeight: string }]> {
  return Object.fromEntries(
    (Object.keys(typography) as TypeToken[]).map((token) => {
      const level = typography[token];
      return [token, [`${level.size}px`, { lineHeight: `${level.lineHeight}px` }]];
    }),
  );
}

/**
 * The `theme.extend` object for apps/mobile/tailwind.config.js.
 *
 * Returned as data rather than written as config so the config file stays a
 * two-line adapter and every value keeps flowing from src/.
 */
export function nativeWindTheme() {
  return {
    colors: colorTheme(),
    // Family names match what @expo-google-fonts registers, and each weight is
    // its own family for the reason given on fontSizeTheme.
    fontFamily: {
      display: ['Manrope_700Bold'],
      'display-hero': ['Manrope_800ExtraBold'],
      'display-soft': ['Manrope_600SemiBold'],
      body: ['Inter_400Regular'],
      'body-medium': ['Inter_500Medium'],
    },
    fontSize: fontSizeTheme(),
    borderRadius: Object.fromEntries(
      Object.entries(radius).map(([token, value]) => [token, `${value}px`]),
    ),
    spacing: Object.fromEntries(
      Object.entries(spacing).map(([token, value]) => [token, `${value}px`]),
    ),
  };
}
