// Emits the generated stylesheets and the NativeWind theme from the compiled
// tokens, so neither app ever restates a token value. Runs after tsc in
// `pnpm build`.
//
// Web gets Tailwind v4 CSS; mobile gets a Tailwind v3 input stylesheet plus a
// CommonJS theme (tailwind.config.js is CJS and cannot require this ESM
// package directly).
import { writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { toTailwindCss } from '../dist/css.js';
import { nativeWindTheme, toNativeWindCss } from '../dist/nativewind.js';

const distDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../dist');

const outputs = [
  ['tokens.css', toTailwindCss()],
  ['nativewind.css', toNativeWindCss()],
  [
    'nativewind-theme.cjs',
    `// GENERATED by @finmanager/tokens - do not edit by hand.\n` +
      `module.exports = ${JSON.stringify(nativeWindTheme(), null, 2)};\n`,
  ],
];

await Promise.all(
  outputs.map(([name, contents]) => writeFile(path.join(distDir, name), contents, 'utf8')),
);

console.log(`tokens: wrote ${outputs.map(([name]) => name).join(', ')}`);
